import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import { StoreProvider } from "@/store/StoreProvider";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KFC - Food delivery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
